<?php

namespace IRPanelQuotes\Controller;

use Cake\Event\Event;
use IRPanelQuotes\Controller\AppController;

class QuotesController extends AppController {

    public $paginate = [
        'limit' => 15,
        'order' => [
            'IRCQuotes.id' => 'desc'
        ]
    ];

    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
    }

    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
    }

    public function search()
    {
        $this->loadModel('IRPanelQuotes.IRCQuotes');

        if($this->request->getMethod() == 'POST') {

            $search = $this->request->getData('search');

            $searchResults = $this->paginate($this->IRCQuotes->find('all')->where([
                'OR' => [
                    ['topic LIKE' => '%' . $search . '%'],
                    ['quote LIKE' => '%' . $search . '%']
                ]
            ]));

            $this->set('results', $searchResults);
        }
    }

    public function view($id = null)
    {
        if($id == null) {

            return $this->redirect('/quotes/browse');
        }

        $this->loadModel('IRPanelQuotes.IRCQuotes');

        $quote = $this->IRCQuotes->find('all', ['contain' => ['IRCUsers']])->where(['IRCQuotes.id' => $id])->first();

        $this->set('quote', $quote);
    }

    public function browse()
    {
        $this->loadModel('IRPanelQuotes.IRCQuotes');

        $quotes = $this->paginate($this->IRCQuotes->find('all', ['contain' => ['IRCUsers']]));

        $this->set('quotes', $quotes);
    }

    public function add()
    {

    }

    public function dashboard()
    {

    }

    public function adminDashboard()
    {

    }
}
